spring.application.name=email-service
server.port=8084

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/email_db
spring.datasource.username=postgres
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Eureka Client Configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# Mail Configuration (Example: Gmail)
# Replace with your actual credentials or instructions
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=omegelalbert@gmail.com
spring.mail.password=mfdetllcdjkgmoce
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# OTP Configuration
otp.expiration.minutes=5
otp.length=6
